import { ClientProvider } from '@/components/ClientProvider'
import { Header } from '@/components/Header'
import { Sidebar } from '@/components/Sidebar'
import '@/styles/globals.css'

export const metadata = {
  title: 'Amazon Web Scrap',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex bg-[#F7FBFF] h-screen">
        <ClientProvider>
          <Sidebar />
          <main className="p-10 max-w-7xl mx-auto flex-1">
            <Header />
            {children}
          </main>
        </ClientProvider>
      </body>
    </html>
  )
}
